// Tailors the canonical resume to a specific job description by
// scoring each bullet's tags against tokens in the JD, reordering
// bullets and skills to surface the most relevant first, then writing
// a tailored DOCX + PDF into ./tailored/.
//
// Usage:
//   npm run tailor -- --jd path/to/jd.txt --output acme
//   cat jd.txt | npm run tailor -- --output acme
//
// Optional:
//   --max-bullets N   trim each role to top-N scoring bullets (default: keep all)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const args = process.argv.slice(2);
const argMap = {};
for (let i = 0; i < args.length; i += 2) argMap[args[i]] = args[i + 1];

const slug = (argMap['--output'] || 'tailored').replace(/[^a-z0-9_-]/gi, '_');
const jdPath = argMap['--jd'];
const maxBullets = argMap['--max-bullets'] ? parseInt(argMap['--max-bullets'], 10) : null;

let jdText;
if (jdPath) {
  jdText = readFileSync(resolve(process.cwd(), jdPath), 'utf8');
} else {
  try {
    jdText = readFileSync(0, 'utf8');
  } catch {
    jdText = '';
  }
}
if (!jdText.trim()) {
  console.error('No JD provided. Pass --jd <path> or pipe JD text via stdin.');
  process.exit(1);
}

const STOPWORDS = new Set([
  'the','and','for','with','our','you','your','will','have','has','any','all',
  'use','using','this','that','from','into','are','was','were','can','they',
  'team','role','job','work','required','requirements','responsibilities',
  'qualifications','about','etc','years','plus','strong','good','excellent',
  'must','should','able','ability','knowledge','experience','candidate',
]);

const tokenize = (s) =>
  s.toLowerCase()
    .replace(/[-_/]/g, ' ')
    .replace(/[^\w\s]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length > 1);

const jdTokens = new Set(tokenize(jdText).filter((t) => !STOPWORDS.has(t)));

const scoreTag = (tag) => {
  const parts = tokenize(tag);
  if (parts.length === 0) return 0;
  if (parts.every((p) => jdTokens.has(p))) return parts.length * 2;
  if (parts.some((p) => jdTokens.has(p))) return 1;
  return 0;
};

const scoreBullet = (b) => {
  if (typeof b === 'string') return 0;
  return (b.tags || []).reduce((s, t) => s + scoreTag(t), 0);
};

const data = await import(pathToFileURL(resolve(repoRoot, 'src/data/resume.mjs')).href);

const tailoredExperiences = data.experiences.map((exp) => {
  const ranked = exp.points
    .map((p, i) => ({ p, i, score: scoreBullet(p) }))
    .sort((a, bb) => (bb.score - a.score) || (a.i - bb.i))
    .map((x) => x.p);
  return { ...exp, points: maxBullets ? ranked.slice(0, maxBullets) : ranked };
});

const skillScores = data.skillNames.map((s) => ({ s, score: scoreTag(s) }));
const matched = skillScores
  .filter((x) => x.score > 0)
  .sort((a, b) => b.score - a.score)
  .map((x) => x.s);
const matchedSet = new Set(matched);
const remaining = data.skillNames.filter((s) => !matchedSet.has(s));
const tailoredSkillNames = [...matched, ...remaining];

// Re-sort inside each skill group too, so the JD-relevant tools lead
// their line on the rendered CV rather than only the flat list.
const tailoredSkillGroups = data.skillGroups.map((g) => ({
  ...g,
  items: [...g.items].sort((a, b) => scoreTag(b) - scoreTag(a)),
}));

const tailored = {
  personal: data.personal,
  headline: data.headline,
  highlights: data.highlights,
  summary: data.summary,
  skillGroups: tailoredSkillGroups,
  skillNames: tailoredSkillNames,
  experiences: tailoredExperiences,
  education: data.education,
};

const tailoredDir = resolve(repoRoot, 'tailored');
mkdirSync(tailoredDir, { recursive: true });

const dataModulePath = resolve(tailoredDir, `${slug}.data.mjs`);
const moduleSource = `// Auto-generated by scripts/tailor-cv.mjs from ${jdPath || 'stdin JD'}.
export const personal = ${JSON.stringify(tailored.personal, null, 2)};
export const headline = ${JSON.stringify(tailored.headline, null, 2)};
export const highlights = ${JSON.stringify(tailored.highlights, null, 2)};
export const summary = ${JSON.stringify(tailored.summary, null, 2)};
export const skillGroups = ${JSON.stringify(tailored.skillGroups, null, 2)};
export const skillNames = ${JSON.stringify(tailored.skillNames, null, 2)};
export const experiences = ${JSON.stringify(tailored.experiences, null, 2)};
export const education = ${JSON.stringify(tailored.education, null, 2)};
`;
writeFileSync(dataModulePath, moduleSource);

const docxOut = resolve(tailoredDir, `KRISH_PAVULURI_CV_${slug}.docx`);
const pdfOut = resolve(tailoredDir, `KRISH_PAVULURI_CV_${slug}.pdf`);

const matchedTokens = [...jdTokens].slice(0, 25).join(', ');
console.log(`Top JD tokens (sample): ${matchedTokens}`);
console.log(`Matched skills surfaced: ${matched.join(', ') || '(none)'}`);
console.log(`Tailored data → ${dataModulePath}`);

console.log('\nGenerating DOCX...');
let res = spawnSync('node', [
  resolve(repoRoot, 'scripts/generate-docx.mjs'),
  '--data', dataModulePath,
  '--output', docxOut,
], { stdio: 'inherit' });
if (res.status !== 0) process.exit(res.status);

console.log('Generating PDF...');
res = spawnSync('npx', [
  'tsx',
  resolve(repoRoot, 'scripts/generate-pdf.tsx'),
  '--data', dataModulePath,
  '--output', pdfOut,
], { stdio: 'inherit' });
if (res.status !== 0) process.exit(res.status);

console.log(`\nDone:`);
console.log(`  ${docxOut}`);
console.log(`  ${pdfOut}`);
